<?php

namespace ContainerBa0A7Ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JNNfprKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jNNfprK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jNNfprK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'animal' => ['privates', 'App\\Repository\\AnimauxRepository', 'getAnimauxRepositoryService', true],
            'article' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
        ], [
            'animal' => 'App\\Repository\\AnimauxRepository',
            'article' => 'App\\Repository\\ArticlesRepository',
        ]);
    }
}
