<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHPGU4x6\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHPGU4x6/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHPGU4x6.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHPGU4x6\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerHPGU4x6\App_KernelProdContainer([
    'container.build_hash' => 'HPGU4x6',
    'container.build_id' => '1022ebb1',
    'container.build_time' => 1624461150,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHPGU4x6');
