<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBa0A7Ua\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBa0A7Ua/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBa0A7Ua.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBa0A7Ua\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBa0A7Ua\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ba0A7Ua',
    'container.build_id' => '7f53384d',
    'container.build_time' => 1624615350,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBa0A7Ua');
