<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'animaux' => [[], ['_controller' => 'App\\Controller\\AnimauxController::index'], [], [['text', '/animaux']], [], []],
    'animal' => [['id'], ['_controller' => 'App\\Controller\\AnimauxController::animal'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/animaux/single']], [], []],
    'articles' => [[], ['_controller' => 'App\\Controller\\ArticleController::index'], [], [['text', '/article']], [], []],
    'article' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::article'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article/single']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'panier' => [[], ['_controller' => 'App\\Controller\\PanierController::index'], [], [['text', '/panier']], [], []],
    'panier_add_article' => [['id'], ['_controller' => 'App\\Controller\\PanierController::addArticle'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/panier/addArticle']], [], []],
    'panier_add_animal' => [['id'], ['_controller' => 'App\\Controller\\PanierController::addAnimal'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/panier/addAnimal']], [], []],
    'panier_remove_article' => [['id'], ['_controller' => 'App\\Controller\\PanierController::removeArticle'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/panier/removeArticle']], [], []],
    'panier_remove_animal' => [['id'], ['_controller' => 'App\\Controller\\PanierController::removeAnimal'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/panier/removeAnimal']], [], []],
    'register_don' => [[], ['_controller' => 'App\\Controller\\RegisterDonController::index'], [], [['text', '/registerBanq']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/inscription']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/connexion']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
